---
- name: Install Java
  yum:
    name: java-11-openjdk
    state: present

- name: Import Elasticsearch GPG key
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticsearch repository
  yum_repository:
    name: elasticsearch
    description: Elasticsearch Repository
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Start and enable Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  yum:
    name: kibana
    state: present

- name: Start and enable Kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- name: Install Logstash
  yum:
    name: logstash
    state: present

- name: Start and enable Logstash service
  service:
    name: logstash
    state: started
    enabled: yes

